### ISSUE TITLE
API Key Missing

### ISSUE THREAD

**Issue by richardkeller411** [datocms/react-demo#1]
Image not found https://www.datocms.com/static/api-token-5afae851cb5efd1ea2abfc41741d7b96-95c66.png   .

Lots of updates needed to yarn in node sass and a few other deprecated libraries.   Demo won't work.

**Comment by matjack1** [comment]
This is now fixed with a handy button that lets you replicate the project under your account :)

[![Deploy with DatoCMS](https://dashboard.datocms.com/deploy/button.svg)](https://dashboard.datocms.com/deploy?repo=datocms/react-demo)
